// <auto-generated />
using System;
using Icon.DesignPattern.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Icon.DesignPattern.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221119103340_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Icon.DesignPattern.DataAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CellPhone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smartwatch"
                        });
                });

            modelBuilder.Entity("Icon.DesignPattern.DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "CellPhone 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "CellPhone 1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Laptop 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Laptop 1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Tablet 1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Tablet 1"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Smartwatch 1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Smartwatch 1"
                        });
                });

            modelBuilder.Entity("Icon.DesignPattern.DataAccess.Models.Product", b =>
                {
                    b.HasOne("Icon.DesignPattern.DataAccess.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Icon.DesignPattern.DataAccess.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
